#!/bin/sh
# Rebuilds requirements.lock: every package Keybo, its tests and its builds need, with exact versions and hashes,
# for every system (Mac, Windows, Linux) and Python 3.11 and newer. CI and the builds install only from it
# (pip install --require-hashes -r requirements.lock), so a package cannot change or be swapped unnoticed.
# Run it after changing any requirements*.txt, including on a Dependabot pull request; CI checks it is current.
set -eu
cd "$(dirname "$0")/.."
{
  echo "# Generated by scripts/lock.sh from requirements-dev.txt and requirements-build.txt. Do not edit by hand."
  uv pip compile requirements-dev.txt requirements-build.txt --universal --generate-hashes --python-version 3.11 --no-header -q
} > requirements.lock
